flags:
  hmatrix-special:
    safe-cheap: false
  hmatrix-tests:
    gsl: true
  hmatrix:
    openblas: false
  hmatrix-gsl:
    onlygsl: false
packages:
- packages/tests/
- packages/special/
- packages/gsl/
- packages/glpk/
- packages/base/
- packages/sundials/
- examples/
extra-deps:
- diagrams-rasterific-1.4
- plots-0.1.0.2
resolver: lts-10.9
nix:
  path: [nixpkgs=./nixpkgs.nix]
  shell-file: shell.nix
