flags:
#  hmatrix-special:
#    safe-cheap: false
  hmatrix-tests:
    gsl: false
  hmatrix:
    openblas: true
#  hmatrix-gsl:
#    onlygsl: false
packages:
- packages/tests/
#- packages/special/
#- packages/sparse/
#- packages/gsl/
#- packages/glpk/
- packages/base/
extra-deps: []
resolver: lts-3.11
