version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:haskell
    steps:
      - checkout
      - restore_cache:
          key: stack-deps-urk-{{ checksum "stack.yaml" }}
      - run:
          name: Update packages
          command: nix-channel --update
      - run:
          name: Setup build toolchain
          command: nix-shell --run "stack setup"
      - run:
          name: Building dependencies
          command: nix-shell --run "stack test --only-snapshot --prefetch"
      - save_cache:
          paths:
            - "~/.stack"
          key: stack-deps-urk-{{ checksum "stack.yaml" }}
      - run:
          name: Building
          command: nix-shell --run "stack build --pedantic"
      - run:
          name: Building tests
          command: nix-shell --run "stack test --pedantic --no-run-tests"
      - run:
          name: Running tests
          command: nix-shell --run "stack test"
